/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GlassCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/LuxeHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/StyledText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EditScreenInfo`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Themed`; params?: Router.UnknownInputParams; } | { pathname: `/../context/WishlistContext`; params?: Router.UnknownInputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/product/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wishlist` | `/wishlist`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/GlassCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/LuxeHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/StyledText`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/EditScreenInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Themed`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/WishlistContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/product/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/shop` | `/shop`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/wishlist` | `/wishlist`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/settings${`?${string}` | `#${string}` | ''}` | `/../components/ExternalLink${`?${string}` | `#${string}` | ''}` | `/../components/GlassCard${`?${string}` | `#${string}` | ''}` | `/../components/LuxeHeader${`?${string}` | `#${string}` | ''}` | `/../components/StyledText${`?${string}` | `#${string}` | ''}` | `/../components/EditScreenInfo${`?${string}` | `#${string}` | ''}` | `/../components/Themed${`?${string}` | `#${string}` | ''}` | `/../context/WishlistContext${`?${string}` | `#${string}` | ''}` | `/../context/CartContext${`?${string}` | `#${string}` | ''}` | `/product/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/shop${`?${string}` | `#${string}` | ''}` | `/shop${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/wishlist${`?${string}` | `#${string}` | ''}` | `/wishlist${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GlassCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/LuxeHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/StyledText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EditScreenInfo`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Themed`; params?: Router.UnknownInputParams; } | { pathname: `/../context/WishlistContext`; params?: Router.UnknownInputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/product/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wishlist` | `/wishlist`; params?: Router.UnknownInputParams; };
    }
  }
}
